// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: send-sms.proto

package sendSmsgRPC

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SendSmsgRPCServiceClient is the client API for SendSmsgRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendSmsgRPCServiceClient interface {
	SendSmsToNodeService(ctx context.Context, in *SendSmsgRPCRequest, opts ...grpc.CallOption) (*SendSmsgRPCResponse, error)
}

type sendSmsgRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSendSmsgRPCServiceClient(cc grpc.ClientConnInterface) SendSmsgRPCServiceClient {
	return &sendSmsgRPCServiceClient{cc}
}

func (c *sendSmsgRPCServiceClient) SendSmsToNodeService(ctx context.Context, in *SendSmsgRPCRequest, opts ...grpc.CallOption) (*SendSmsgRPCResponse, error) {
	out := new(SendSmsgRPCResponse)
	err := c.cc.Invoke(ctx, "/sendSms.sendSmsgRPCService/SendSmsToNodeService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendSmsgRPCServiceServer is the server API for SendSmsgRPCService service.
// All implementations must embed UnimplementedSendSmsgRPCServiceServer
// for forward compatibility
type SendSmsgRPCServiceServer interface {
	SendSmsToNodeService(context.Context, *SendSmsgRPCRequest) (*SendSmsgRPCResponse, error)
	mustEmbedUnimplementedSendSmsgRPCServiceServer()
}

// UnimplementedSendSmsgRPCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSendSmsgRPCServiceServer struct {
}

func (UnimplementedSendSmsgRPCServiceServer) SendSmsToNodeService(context.Context, *SendSmsgRPCRequest) (*SendSmsgRPCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSmsToNodeService not implemented")
}
func (UnimplementedSendSmsgRPCServiceServer) mustEmbedUnimplementedSendSmsgRPCServiceServer() {}

// UnsafeSendSmsgRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendSmsgRPCServiceServer will
// result in compilation errors.
type UnsafeSendSmsgRPCServiceServer interface {
	mustEmbedUnimplementedSendSmsgRPCServiceServer()
}

func RegisterSendSmsgRPCServiceServer(s grpc.ServiceRegistrar, srv SendSmsgRPCServiceServer) {
	s.RegisterService(&SendSmsgRPCService_ServiceDesc, srv)
}

func _SendSmsgRPCService_SendSmsToNodeService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSmsgRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendSmsgRPCServiceServer).SendSmsToNodeService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sendSms.sendSmsgRPCService/SendSmsToNodeService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendSmsgRPCServiceServer).SendSmsToNodeService(ctx, req.(*SendSmsgRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SendSmsgRPCService_ServiceDesc is the grpc.ServiceDesc for SendSmsgRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendSmsgRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sendSms.sendSmsgRPCService",
	HandlerType: (*SendSmsgRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSmsToNodeService",
			Handler:    _SendSmsgRPCService_SendSmsToNodeService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "send-sms.proto",
}
